### ISSUE TITLE
unsupported theme option 'sidebar_collapse' given

### ISSUE THREAD

**Issue by dforsi** [junzis/the-1090mhz-riddle#19]
When I run `make html` I get the error
```
unsupported theme option 'sidebar_collapse' given
```
I can build the HTML docs if I remove from `conf.py` the line with that option.

I did a fresh git clone and installed the package python-sphinx (1.6.6-2) on Debian GNU/Linux testing (buster) which pulled the following dependencies:

```
Start-Date: 2018-02-11  13:27:04
Commandline: apt-get install python-sphinx
Requested-By: daniele (1000)
Install: docutils-common:amd64 (0.14+dfsg-2, automatic), python-markupsafe:amd64 (1.0-1+b1,
 automatic), docutils-doc:amd64 (0.14+dfsg-2, automatic), python-docutils:amd64 (0.14+dfsg-2,
 automatic), python-alabaster:amd64 (0.7.8-1, automatic), python-jinja2:amd64 (2.10-1, automatic),
 python-roman:amd64 (2.0.0-3, automatic), python-imagesize:amd64 (0.7.1-1, automatic),
 python-babel-localedata:amd64 (2.4.0+dfsg.1-2, automatic), python-babel:amd64 (2.4.0+dfsg.1-2,
 automatic), python-sphinx:amd64 (1.6.6-2), sphinx-common:amd64 (1.6.6-2, automatic),
 python-typing:amd64 (3.6.2-1, automatic)
End-Date: 2018-02-11  13:28:11
```

**Comment by junzis** [comment]
It is specific to the sphinx theme Alabaster. You will need to install it if it was not included in your Sphinx already: http://alabaster.readthedocs.io/en/latest/installation.html

**Comment by dforsi** [comment]
Thank you, I installed Alabaster with pip following the instructions in that page for older versions of Sphinx because I found that the option `sidebar_collapse` is available since Alabaster v. 0.7.9 (Jul 26, 2016) but Debian still has version 0.7.8. https://packages.debian.org/search?keywords=python-alabaster

**Comment by junzis** [comment]
Indeed, the Linux python-* libraries are often a bit older. PIP is always better in this case.  Cheers.
