### ISSUE TITLE
reference documentation/bibliography

### ISSUE THREAD

**Issue by espinielli** [junzis/the-1090mhz-riddle#25]
I do not know how to do it in .rst files / or with .rst toolset (pandoc?), but I find that it could be useful to have bibliographical references to the standards or other relevant docs...
(Bear with me if these are already mentioned somewhere in the doc and I have not spotted them)

**Comment by junzis** [comment]
There are indeed already at the bottom of ``index.rst``, which appears the end of the homepage. However, they are not particularly well formatted.
