### ISSUE TITLE
please re-instate "edit on github"

### ISSUE THREAD

**Issue by espinielli** [junzis/the-1090mhz-riddle#26]
I think that the "edit on github" facility was a big way to lower the barrier for feedback and review/correction contributions.
Without it, the time needed to set things up is just increasing the time/burden and lowers the probability to get any feedbacks both from (somewhat) skilled geeks and aviation knowledgeable people.
My 2 cents. 😄

**Comment by espinielli** [comment]
Oooops I see you converted the source to LaTeX!!!
So that even makes it more difficult to ever contribute from anybody 👿 !
I have been/am a LaTeX user but with the tools you are using (pandoc) I see little benefits to have it used for something that looks after open source contributions...

Please note this is a personal opinion, and a humble suggestion, and not a criticism on your excellent work.

PS: Personally I have been enjoying markdown a lot and resorted to LaTeX only for very specific tasks...
(For example I have even published a paper using R Markdown [which uses pandoc behind the scenes] via a [rticle package](https://github.com/rstudio/rticles) which supports IEEE Transactions template!!!)

**Comment by junzis** [comment]
I would like to compile the book as nice PDF as well. In this case, there is no better format than latex which generates consistent PDF across the platforms. Now I can simply use ``make pdf`` or ``make html`` to create either.

I will try to add the "edit on github" link back. There are very few difference in modifying ``.rst`` or ``.tex``. The syntaxes are minial as well.

**Comment by junzis** [comment]
fixed in 730ff70 now
