### ISSUE TITLE
Exponent of 2^17 not rendered correctly

### ISSUE THREAD

**Issue by dforsi** [junzis/the-1090mhz-riddle#31]
This line https://github.com/junzis/the-1090mhz-riddle/blob/e627276d5f77dd180f881f4b1e0a2694ae2f180a/adsb/airborne-position.tex#L98 renders as 
![image](https://user-images.githubusercontent.com/1055635/44220746-c900ee00-a17f-11e8-81ba-8a9e23faa62c.png)

**Comment by junzis** [comment]
Fixed now. Thanks!
