### ISSUE TITLE
Question about inferring the comm-B downlink parameters

### ISSUE THREAD

**Issue by marius190** [junzis/the-1090mhz-riddle#39]
I have read your article and had a look at your library pyModeS. I have a question:

- The function **common.icao()** , for message of type Comm-B, I see that just implement the ICAO address recovery logic. So, the resulting ICAO may be incorrect when message is corrupted or when ICAO adress is overlaid with the BDS code. Nevertheless, I see in your article an interesting method to check the veracity of the ICAO address, using the ADS-B data and the Squawk code. Is this implementation available in the pyModeS library?

**Comment by junzis** [comment]
This is not yet implemented directly yet in pyModeS. We should add it at some point to the ``modeslive`` interface.
