### ISSUE TITLE
Preamble Detection

### ISSUE THREAD

**Issue by BismaAmjad** [junzis/the-1090mhz-riddle#41]
Hi, 
   Thanks for compiling an amazing book on understanding the ADSB signal architecture and its decoding procedure. The book is pretty comprehensive, however, I couldn't find the preamble detection method used to identify an ADS-B signal. I want to know exactly:

-  how the raw received data is first converted into binary 
- how to implement preamble detection, before the adsb message could be decoded.

Any help will be highly appreciated.

Thanks
Bisma

**Comment by junzis** [comment]
This will be in a new version of the book, which should be available soon.

For those who are interested now. Here is an implementation in pyModeS:
https://github.com/junzis/pyModeS/blob/master/pyModeS/extra/rtlreader.py
