### ISSUE TITLE
Decode guide about about DF4 DF5 D16 

### ISSUE THREAD

**Issue by Radio-zhang** [junzis/the-1090mhz-riddle#42]
Hi,
The book is pretty comprehensive, however,It’s a pity that the book does not mention the decoding instructions for DF4 DF5 DF16，I sincerely hope that Dr. Sun can provide guidance in this field.I really hope to get your help and look forward to your reply

**Comment by junzis** [comment]
There are chapters in the second edition dealing with these messages now.
