### ISSUE TITLE
ICAO addressses can be changed in military aircraft

### ISSUE THREAD

**Issue by teeks99** [junzis/the-1090mhz-riddle#45]
https://github.com/junzis/the-1090mhz-riddle/blob/90643baa6283f38d5432a89c7958b5dcae6b2803/content/ads-b/1-basics.tex#L56

In the linked section it indicates that 

> A unique ICAO address is assigned to each Mode S transponder of an aircraft and serves as the unique identifier for each aircraft

However, as [this report](https://theaviationist.com/2020/09/29/yes-u-s-rc-135s-have-used-bogus-hex-codes-to-transmit-a-false-identity-but-its-not-to-fool-china-or-other-enemies/) states military aircraft clearly often have a capability to modify the ICAO address. 

It might be worth noting at this point that military aircraft can transmit non-assigned ICAO addresses. Potentially they could transmit anything else in the message, but I'm not sure that is important.

**Comment by junzis** [comment]
That's a very good point. Thank you for pointing it out. 

Apparently, the situation might get worse with the FAA Privacy ICAO Address (PIA) Program, where private airplanes will be able to do the same trick.
