### ISSUE TITLE
Errata: Caption Figure 5.2; "1) ACAS related bits" in Section 16.1

### ISSUE THREAD

**Issue by zveriu** [junzis/the-1090mhz-riddle#49]
https://github.com/junzis/the-1090mhz-riddle/blob/54a87f6cb9fd357ec552cb9dd600282ef625b49d/content/ads-b/3-airborne-position.tex#L68

- Current: Figure 5.2: Simplified CPR position coding (all position possiilities)
- Must be: possibilities

https://github.com/junzis/the-1090mhz-riddle/blob/54a87f6cb9fd357ec552cb9dd600282ef625b49d/content/mode-s/6-els.tex#L52
72|71   37|36   0|0: RTCA/DO-185 (pre-ACAS)
- Current: 37|36
- Must be: 40|39

https://github.com/junzis/the-1090mhz-riddle/blob/54a87f6cb9fd357ec552cb9dd600282ef625b49d/content/mode-s/6-els.tex#L264
- Current: blew
- Must be: below

**Comment by junzis** [comment]
Thank you very much @zveriu for spotting these errors!
