### ISSUE TITLE
Citation not rendered in chapter "Airborne velocity" on website

### ISSUE THREAD

**Issue by dforsi** [junzis/the-1090mhz-riddle#50]
This is a snapshot of the web page at https://mode-s.org/decode/content/ads-b/5-airborne-velocity.html
![image](https://user-images.githubusercontent.com/1055635/105408242-fe527580-5c2e-11eb-85e1-0f9974cfae06.png)
it is missing the citation between the words "in has".

This is a snapshot from the PDF at https://mode-s.org/decode/book-the_1090mhz_riddle-junzi_sun.pdf
![image](https://user-images.githubusercontent.com/1055635/105408623-7d47ae00-5c2f-11eb-8eda-317b14330fad.png)

This is the corresponding source text:
> For instance, the study in \cite{stone2015} has made use of the later information to

**Comment by junzis** [comment]
The citations on the website are fixed now.
