### ISSUE TITLE
Wrong sign in the vertical rate formula

### ISSUE THREAD

**Issue by ajuch** [junzis/the-1090mhz-riddle#52]
Hi,

I implemented some decoding functions based on your great book but I noticed that the formula of the vertical speed (7.1) has the wrong sign. The formula is written as `VS = (2S_vr - 1) * 64 * (V_r - 1)` but this conflicts with the meaning of `S_vr = 0` is climb. Also the examples 7.2 and 7.3 have this mistake.

Br, Andreas

**Comment by junzis** [comment]
Hi @ajuch, you are correct. The formula should be (1 - 2 Svr) x 64 x (Vr -1). I will update this in a new commit.

**Comment by junzis** [comment]
fixed with updates equations now.
