### ISSUE TITLE
\0 and \1 not rendered in HTML version

### ISSUE THREAD

**Issue by dforsi** [junzis/the-1090mhz-riddle#56]
The codes for \0 and \1 aren't rendered in several places of the HTML version of the book.

For example, in the introduction https://mode-s.org/decode/content/introduction.html#mode-s-replies

the source text:
> The \0 bit is reversed compared to the \1 bit

is rendered as:
> The bit is reversed compared to the bit

while it is rendered correctly in the PDF version:
> ![image](https://user-images.githubusercontent.com/1055635/117570807-2fff2780-b0cc-11eb-9cf8-d118986e0996.png)

**Comment by junzis** [comment]
Thank you @dforsi. This is fixed now.
