### ISSUE TITLE
More formatting could be added for "Note" and "Try it out" labels in HTML version

### ISSUE THREAD

**Issue by dforsi** [junzis/the-1090mhz-riddle#57]
The word "Note" is rendered near to the following text, which reduces legibility compared to the PDF version. I think that appending ":" would be enough.

This is the HTML version:
> ![image](https://user-images.githubusercontent.com/1055635/117571459-f67beb80-b0ce-11eb-8864-5b6ea77ddde4.png)

This is the PDF version:
> ![image](https://user-images.githubusercontent.com/1055635/117571426-caf90100-b0ce-11eb-8e09-d0f28f0f8e59.png)

**Comment by junzis** [comment]
Thank you @dforsi. This is improved now.
